// app/layout.tsx
import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import './globals.css';
import '../styles/nprogress.css';
import { Toaster } from 'sonner';
import Navbar from '@/components/Navbar';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppProvider } from '@/contexts/AppProvider';
import RouteProgress from '@/components/route/RouteProgress';
import { ThemeProvider } from '@/components/providers/ThemeProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Fast Food App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true';

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
        <AppProvider>
          <RouteProgress />
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
            <Toaster richColors position="bottom-center" closeButton />
          <SidebarProvider>
            <main className="w-full">
              <Navbar />
              <div className="px-4 mb-5">{children}</div>
            </main>
          </SidebarProvider>
          </ThemeProvider>
          
        </AppProvider>
      </body>
    </html>
  );
}
